# -*- coding: utf-8 -*-
# Renvois conseillés : (tranche, ligne FR de l'en-tête ou de la ligne-titre, regex EN de l'en-tête correspondant, [instruments])
R = [
 ('tete_volet1', 132, r'^### Q4\.', ['sonde', 'orga', 'cas', 'eval']),
 ('tete_volet1', 138, r'^### Q5\.', ['cot']),
 ('tete_volet1', 162, r'^### Q10\.', ['moni', 'sonde']),
 ('tete_volet1', 168, r'^### Q11\.', ['red', 'moni']),
 ('volet_M', 345, r'^## M8 ', ['sonde', 'juge']),
 ('volet_M', 365, r'^## M9 ', ['red', 'classif', 'unl']),
 ('volet2_A_a_D', 442, r'^### Worked case — model organisms', ['sonde', 'cas']),
 ('volet2_A_a_D', 488, r'^### Worked case — evaluations', ['cas', 'sonde']),
 ('volet2_A_a_D', 523, r'^### Worked case — probes and steering', ['alea', 'degr']),
 ('volet2_A_a_D', 589, r'^### Worked case — the workspace', ['abl', 'degr', 'cot']),
 ('volet2_E_a_I', 675, r'^### Worked case — scalable oversight', ['orga', 'sonde']),
 ('volet2_E_a_I', 760, r'^### Worked case — monitoring', ['sonde', 'red', 'cas']),
 ('volet2_E_a_I', 842, r'^### Worked case — training interventions', ['cas']),
 ('volet3', 923, r'^### 2\. Evaluating alignment', ['eval', 'auto', 'orga']),
 ('volet3', 953, r'^### 3\. Control through monitoring', ['moni', 'sonde', 'nla']),
 ('volet3', 977, r'^### 4\. Scalable oversight', ['sonde', 'debat', 'w2s', 'elic']),
 ('volet3', 1003, r'^### 5\. Adversarial robustness', ['red', 'classif']),
 ('volet3', 1029, r'^### 6\. The "miscellaneous"', ['unl']),
 ('volets4_5_entete', 1119, r'^Sleeper Agents \(Anthropic, Hubinger', ['orga', 'red']),
 ('volets4_5_entete', 1139, r'^Representation Engineering \(RepE\)', ['sonde', 'pilot', 'elic']),
 ('volets4_5_entete', 1185, r'^Auditing Hidden Objectives \(Anthropic', ['orga', 'sae']),
 ('volets4_5_entete', 1203, r'^Unlearning put to the test|^The unlearning put to the test|^Unlearning .*Deeb', ['unl']),
 ('volets4_5_entete', 1253, r'^Topic 1 — ', ['sonde', 'det', 'moni']),
 ('volets4_5_entete', 1257, r'^Topic 2 — ', ['pilot', 'abl', 'degr', 'alea']),
 ('volets4_5_entete', 1261, r'^Topic 3 — ', ['sae', 'graph', 'abl']),
 ('volets4_5_entete', 1267, r'^Topic 4 — ', ['cot', 'nla', 'sonde', 'jlens']),
 ('volets4_5_entete', 1271, r'^Topic 6 — ', ['sonde', 'elic', 'det']),
 ('volets4_5_entete', 1275, r'^Topic 10 — ', ['pilot']),
 ('volets4_5_entete', 1287, r'^Topic 5 — ', ['orga', 'cas']),
 ('volets4_5_entete', 1291, r'^Topic 8 — ', ['moni', 'red']),
 ('volets4_5_entete', 1295, r'^Topic 9 — ', ['orga', 'sae', 'graph']),
 ('volets4_5_entete', 1299, r'^Topic 7 — ', ['cot']),
 ('volets4_5_entete', 1307, r'^Topic 12 — ', ['w2s', 'debat']),
 ('volet6', 1402, r'^### 2\. Your results', ['abl', 'patch', 'alea']),
 ('volet6', 1451, r'^### 3\. The three controls', ['alea', 'degr']),
 ('volet6', 1499, r'^### 6\. Your research program', ['moni', 'jlens', 'abl']),
 ('volet6', 1578, r'^### 8 · Out-of-distribution validity', ['sonde', 'det', 'orga', 'cas', 'jlens']),
 ('volet7_B_et_D', 1635, r'^### F·22 ', ['moni', 'juge']),
 ('volet7_B_et_D', 1690, r'^### F·23 ', ['moni']),
 ('volet7_B_et_D', 1729, r'^### F·24 ', ['red', 'moni']),
 ('volet7_B_et_D', 1753, r'^### F·25 ', ['eval', 'juge']),
 ('volet7_B_et_D', 1812, r'^### F·30 ', ['nla', 'oracle', 'sae', 'auto']),
 ('volet7_B_et_D', 1843, r'^### F·34 ', ['eval', 'tenu']),
 ('volet7_B_et_D', 1901, r'^### F·31 ', ['pilot', 'sonde']),
 ('volet7_B_et_D', 1928, r'^### F·32 ', ['orga']),
 ('volet7_B_et_D', 1961, r'^### F·38 ', ['eval', 'orga']),
 ('volet7_B_et_D', 1979, r'^### F·28 ', ['auto']),
 ('volet7_B_et_D', 1988, r'^### F·27 ', ['orga']),
 ('volet7_B_et_D', 1994, r'^### F·35 ', ['classif', 'red']),
 ('volet7_B_et_D', 2000, r'^### F·36 ', ['unl']),
 ('volet7_B_et_D', 2012, r'^### F·40 ', ['w2s']),
 ('volet7_B_et_D', 2022, r'^### F·41 ', ['juge']),
 ('volet7_B_et_D', 2032, r'^### F·26 ', ['eval', 'w2s']),
 ('volet7_B_et_D', 2051, r'^### F·60 ', ['moni']),
 ('volet7_B_et_D', 2062, r'^### F·62 ', ['sonde', 'det', 'pilot']),
 ('volet7_A_et_C', 2072, r'^### F·1 ', ['orga', 'sonde']),
 ('volet7_A_et_C', 2098, r'^### F·2 ', ['eval', 'cot']),
 ('volet7_A_et_C', 2124, r'^### F·3 ', ['eval']),
 ('volet7_A_et_C', 2152, r'^### F·4 ', ['sonde', 'pilot']),
 ('volet7_A_et_C', 2176, r'^### F·5 ', ['sonde', 'pilot']),
 ('volet7_A_et_C', 2200, r'^### F·6 ', ['elic']),
 ('volet7_A_et_C', 2224, r'^### F·7 ', ['pilot']),
 ('volet7_A_et_C', 2249, r'^### F·8 ', ['sae']),
 ('volet7_A_et_C', 2274, r'^### F·9 ', ['graph']),
 ('volet7_A_et_C', 2304, r'^### F·10 ', ['moni', 'red']),
 ('volet7_A_et_C', 2328, r'^### F·11 ', ['debat']),
 ('volet7_A_et_C', 2352, r'^### F·12 ', ['w2s']),
 ('volet7_A_et_C', 2376, r'^### F·13 ', ['orga', 'sae']),
 ('volet7_A_et_C', 2424, r'^### F·15 ', ['red']),
 ('volet7_A_et_C', 2472, r'^### F·17 ', ['unl']),
 ('volet7_A_et_C', 2504, r'^### F·50 ', ['sonde', 'moni']),
 ('volet7_A_et_C', 2522, r'^### F·51 ', ['sonde', 'moni']),
 ('volet7_A_et_C', 2540, r'^### F·52 ', ['moni']),
 ('volet7_A_et_C', 2558, r'^### F·53 ', ['moni', 'sonde']),
 ('volet7_A_et_C', 2575, r'^### F·54 ', ['moni']),
 ('volet7_A_et_C', 2610, r'^### F·56 ', ['moni']),
 ('volet7_A_et_C', 2629, r'^### F·57 ', ['eval', 'moni']),
 ('volets8_9', 2763, r'^### 3 · Understanding model cognition', ['auto', 'nla', 'oracle']),
 ('volets8_9', 2786, r'^### 5 · Chain-of-thought faithfulness', ['cot']),
 ('volets8_9', 2798, r'^### 6 · AI control', ['moni', 'sonde']),
 ('volets8_9', 2842, r'^### 7 · Scalable oversight', ['debat', 'w2s', 'elic', 'sonde']),
 ('volets8_9', 2890, r'^### 8 · Adversarial robustness', ['red', 'classif']),
 ('volets8_9', 2912, r'^### 9 · Miscellaneous', ['unl']),
 ('volet10', 3071, r'^### AI Sandbagging', ['eval']),
 ('volet10', 3086, r'^### Me, Myself, and AI', ['eval', 'auto']),
 ('volet10', 3128, r'^### Looking Inward', ['auto']),
 ('volet10', 3138, r'^### SelfIE', ['oracle', 'auto']),
 ('volet10', 3179, r'^## Evaluating alignment › Chain-of-thought faithfulness', ['cot']),
 ('volet10', 3264, r'^## AI control › Activation monitoring', ['sonde', 'moni']),
 ('volet10', 3287, r'^## AI control › Anomaly detection', ['moni', 'elic']),
 ('volet10', 3325, r'^## Scalable oversight › Recursive oversight', ['debat', 'juge']),
 ('volet10', 3400, r'^## Scalable oversight › Weak-to-strong', ['w2s']),
 ('volet10', 3477, r'^## Scalable oversight › Honesty', ['sonde', 'pilot', 'elic']),
 ('volet10', 3565, r'^## Adversarial robustness › Realistic', ['red', 'eval']),
 ('volet10', 3608, r'^## Adversarial robustness › Adaptive', ['red', 'classif']),
 ('volet10', 3621, r'^## Miscellaneous › Unlearning', ['unl']),
 ('volet11_1_a_20', 3673, r'^## 1 · ', ['abl', 'sonde']),
 ('volet11_1_a_20', 3704, r'^## 2 · ', ['abl', 'degr', 'juge']),
 ('volet11_1_a_20', 3727, r'^## 3 · ', ['pilot', 'abl']),
 ('volet11_1_a_20', 3747, r'^## 4 · ', ['abl', 'juge']),
 ('volet11_1_a_20', 3775, r'^## 6 · ', ['sonde', 'orga', 'cas', 'jlens']),
 ('volet11_1_a_20', 3809, r'^## 7 · ', ['red', 'classif', 'unl']),
 ('volet11_1_a_20', 3829, r'^## 8 · ', ['eval', 'tenu']),
 ('volet11_1_a_20', 3878, r'^## 10 · ', ['moni']),
 ('volet11_1_a_20', 3898, r'^## 11 · ', ['sonde', 'pilot', 'moni']),
 ('volet11_1_a_20', 4079, r'^## 19 · ', ['eval', 'jlens', 'pilot']),
 ('volet11_1_a_20', 4102, r'^## 20 · ', ['moni', 'sonde']),
 ('volet11_21_a_52', 4129, r'^## 21 · ', ['sonde', 'orga', 'tenu']),
 ('volet11_21_a_52', 4156, r'^## 22 · ', ['sonde', 'elic', 'juge']),
 ('volet11_21_a_52', 4177, r'^## 23 · ', ['moni']),
 ('volet11_21_a_52', 4187, r'^## 24 · ', ['sonde', 'cas']),
 ('volet11_21_a_52', 4235, r'^## 27 · ', ['eval', 'orga']),
 ('volet11_21_a_52', 4255, r'^## 28 · ', ['eval', 'cot', 'orga']),
 ('volet11_21_a_52', 4273, r'^## 29 · ', ['pilot']),
 ('volet11_21_a_52', 4336, r'^## 32 · ', ['moni', 'red']),
 ('volet11_21_a_52', 4361, r'^## 33 · ', ['moni']),
 ('volet11_21_a_52', 4408, r'^## 35 · ', ['det']),
 ('volet11_21_a_52', 4473, r'^## 38 · ', ['nla', 'oracle', 'sae', 'auto']),
 ('volet11_21_a_52', 4545, r'^## 42 · ', ['orga', 'eval']),
 ('volet11_21_a_52', 4585, r'^## 44 · ', ['eval']),
 ('volet11_21_a_52', 4605, r'^## 45 · ', ['auto']),
 ('volet11_21_a_52', 4657, r'^## 48 · ', ['orga']),
 ('volet11_21_a_52', 4676, r'^## 49 · ', ['w2s']),
 ('volet11_21_a_52', 4694, r'^## 50 · ', ['red']),
 ('volet11_21_a_52', 4709, r'^## 51 · ', ['unl']),
 ('volet11_53_et_fin', 4776, r'^## 56 · ', ['sonde', 'orga', 'eval']),
 ('volet11_53_et_fin', 4793, r'^## 58 · ', ['eval']),
 ('volet11_53_et_fin', 4822, r'^## 60 · ', ['moni']),
 ('volet11_53_et_fin', 4836, r'^## 61 · ', ['red']),
 ('volet11_53_et_fin', 4938, r'^## A3 · ', ['cas', 'sonde']),
 ('volet11_53_et_fin', 4950, r'^## A4 · ', ['abl']),
 ('volet11_53_et_fin', 4977, r'^## A6 · ', ['moni']),
 ('volet11_53_et_fin', 4991, r'^## A7 · ', ['alea', 'degr', 'patch', 'pilot']),
 ('volet11_53_et_fin', 5096, r'^## B2 · ', ['eval']),
 ('volet11_53_et_fin', 5141, r'^## B4 · ', ['nla', 'jlens', 'cot', 'sonde']),
 ('volet11_53_et_fin', 5246, r'^## B9 · ', ['eval', 'unl']),
 ('volet11_53_et_fin', 5269, r'^## B10 · ', ['moni']),
 ('volet11_53_et_fin', 5292, r'^## B11 · ', ['cot', 'auto']),
 ('volet11_53_et_fin', 5336, r'^## B13 · ', ['det', 'sonde']),
 ('volet11_53_et_fin', 5358, r'^## B14 · ', ['red']),
]

# Avertissements ponctuels prêts : (tranche, ligne FR d'ancrage, ligne EN d'ancrage, [instruments], texte FR, texte EN)
P = [
 ('tete_volet1', 140, 200, ['cot'],
  "> ⚠ *(v3.6)* Le raisonnement écrit peut aussi persuader le moniteur : un moniteur fondé sur la chaîne de pensée n'aurait signalé qu'environ 1 % des actions de Mythos 5, contre environ 50 % sans elle — un seul moniteur, un incident (fiche 3). Parade : juger ce que le modèle fait, pas ce qu'il en dit (passation, §5.1) ; encadré complet au volet 11, réponse 43.",
  "> ⚠ *(v3.6)* The written reasoning can also persuade the monitor: a chain-of-thought-based monitor would have flagged only about 1% of Mythos 5's actions, against about 50% without it — one monitor, one incident (reading sheet 3). Workaround: judge what the model does, not what it says about it (handover, §5.1); full box in Part 11, answer 43."),
 ('volet3', 1001, 1126, ['sonde', 'cas'],
  "> ⚠ *(v3.6)* La sonde de défection a été validée sur une porte implantée : la meilleure de 1 000 directions aléatoires y atteint déjà 95,3 %, et la saillance peut venir de l'insertion (fiche 15). Un succès sur organisme borne l'instrument ; pour un modèle devenu trompeur de lui-même, aucune parade connue (cours, volet M, M5).",
  "> ⚠ *(v3.6)* The defection probe was validated on an implanted backdoor: the best of 1,000 random directions already reaches 95.3% there, and salience may come from the insertion (reading sheet 15). A success on an organism bounds the instrument; for a model that became deceptive on its own, no workaround is known (course, Part M, M5)."),
 ('volets4_5_entete', 1149, 1291, ['pilot', 'alea', 'degr'],
  "> ⚠ *(v3.6)* « Augmenter ou diminuer un comportement » ne dit le concept qu'à dégradation appariée : une direction aléatoire de même norme n'en est que le nul de spécificité, et chaque direction pilotée dégrade la sortie (fiche 2 ; cours, volet M, M4). Dans ton dépôt, l'addition d'activations contrastives forçait un artefact de polarité oui/non (README du dépôt).",
  "> ⚠ *(v3.6)* \"Increasing or decreasing a behaviour\" shows the concept only at matched degradation: a matched-norm random direction is only its specificity null, and every steered direction degrades the output (reading sheet 2; course, Part M, M4). In your repository, contrastive activation addition forced a yes/no polarity artefact (repository README)."),
 ('volets4_5_entete', 1269, 1447, ['cot', 'nla', 'pilot'],
  "> ⚠ *(v3.6)* Dans cette triangulation, la verbalisation n'est jamais une preuve d'inhibition : des directions aléatoires la font baisser aussi ; critère principal comportemental, sonde latente en contrôle (programme, partie 8). Et les trois mesures de la conscience d'évaluation ne sont que faiblement corrélées : dire laquelle a fondé quel chiffre (fiche 2).",
  "> ⚠ *(v3.6)* In this triangulation, verbalization is never proof of inhibition: random directions lower it too; behavioural main criterion, latent probe as a control (programme, part 8). And the three measures of evaluation awareness are only weakly correlated: say which one grounded which number (reading sheet 2)."),
 ('volet7_B_et_D', 1915, 2080, ['pilot'],
  "> ⚠ *(v3.6)* Le lien entre déplacement et trait est corrélationnel, le trait se nomme d'avance et l'évaluation est légère (fiche 8) : pour la causalité, le test à dégradation appariée (cours, volet M, M4). Et piloter loin d'une persona pendant l'entraînement aurait doublé la diffusion du désalignement (rapport d'antériorité 3 du 2 octobre — rapport, non vérifié).",
  "> ⚠ *(v3.6)* The shift-to-trait link is correlational, the trait must be named in advance and the evaluation is light (reading sheet 8): for causality, the matched-degradation test (course, Part M, M4). And steering away from a persona during training reportedly doubled the spread of misalignment (prior-art report 3 of 2 October — report, unverified)."),
 ('volet7_A_et_C', 2080, 2214, ['sonde', 'orga', 'cas'],
  "> ⚠ *(v3.6)* Ces sondes ont été validées sur une porte implantée : la meilleure de 1 000 directions aléatoires y atteint déjà 95,3 %, et la saillance pourrait venir de l'insertion (fiche 15). Un succès sur organisme est un cas connu de l'instrument, pas une preuve sur le cas naturel (cours, volet M, M5).",
  "> ⚠ *(v3.6)* These probes were validated on an implanted backdoor: the best of 1,000 random directions already reaches 95.3% there, and salience might come from the insertion (reading sheet 15). A success on an organism is a known case for the instrument, not proof about the natural case (course, Part M, M5)."),
 ('volet7_A_et_C', 2157, 2291, ['pilot', 'alea', 'degr'],
  "> ⚠ *(v3.6)* « L'intervention change le comportement » ne dit le concept qu'à dégradation appariée : une direction aléatoire de même norme n'en est que le nul de spécificité (fiches, partie B, piège 4 ; cours, volet M, M4).",
  "> ⚠ *(v3.6)* \"Intervention changes behaviour\" shows the concept only at matched degradation: a matched-norm random direction is only its specificity null (reading sheets, part B, trap 4; course, Part M, M4)."),
 ('volet7_A_et_C', 2509, 2641, ['sonde', 'moni'],
  "> ⚠ *(v3.6)* Le volet 6, §6 attribue 0,867 à la reproduction de Casademunt et donne aux auteurs « catches 95-99 % » à 1 % de faux positifs, sur leurs propres bancs : dire de quel banc et de quelle étude vient le chiffre (cours, volet 6, §6). Et sur l'honnêteté, des sondes de vérité ont fait moins bien qu'un simple prompt (cours, volet 7, F·62).",
  "> ⚠ *(v3.6)* Part 6, §6 attributes 0.867 to Casademunt's reproduction and gives the authors \"catches 95-99%\" at 1% false positives, on their own benches: say which bench and which study the number comes from (course, Part 6, §6). And on honesty, truth probes did worse than a plain prompt (course, Part 7, F·62)."),
 ('volet11_21_a_52', 4194, 4469, ['sonde'],
  "> ⚠ *(v3.6)* Après un entraînement, une sonde calibrée ailleurs lit autrement : des sondes neuves hors domaine se dégradent après RL (rapport d'antériorité 3 du 2 octobre — rapport), et une sonde évaluation contre déploiement basculerait sur les cas limites sans que la réentraîner récupère presque rien (rapport d'antériorité 4 du 2 octobre — résumé seul, à vérifier). Parade : une sonde neuve par bras et après l'entraînement, sur un jeu d'indices disjoint (passation, §5.2) ; contre la bascule sous RL, aucune parade connue.",
  "> ⚠ *(v3.6)* After training, a probe calibrated elsewhere reads differently: fresh out-of-domain probes degrade after RL (prior-art report 3 of 2 October — report), and an evaluation-versus-deployment probe would flip on edge cases with retraining recovering almost nothing (prior-art report 4 of 2 October — abstract only, to be checked). Workaround: a fresh probe per arm and after training, on a disjoint cue set (handover, §5.2); against the flip under RL, none known."),
]
